# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnina_embeddings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gnina_embeddings.proto',
  package='gnina_autoencoder',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16gnina_embeddings.proto\x12\x11gnina_autoencoder\"-\n\x06ligand\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x15\n\tembedding\x18\x02 \x03(\x02\x42\x02\x10\x01\"B\n\x07protein\x12\x0c\n\x04path\x18\x01 \x01(\t\x12)\n\x06ligand\x18\x02 \x03(\x0b\x32\x19.gnina_autoencoder.ligandb\x06proto3'
)




_LIGAND = _descriptor.Descriptor(
  name='ligand',
  full_name='gnina_autoencoder.ligand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='gnina_autoencoder.ligand.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='embedding', full_name='gnina_autoencoder.ligand.embedding', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=90,
)


_PROTEIN = _descriptor.Descriptor(
  name='protein',
  full_name='gnina_autoencoder.protein',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='gnina_autoencoder.protein.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ligand', full_name='gnina_autoencoder.protein.ligand', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=158,
)

_PROTEIN.fields_by_name['ligand'].message_type = _LIGAND
DESCRIPTOR.message_types_by_name['ligand'] = _LIGAND
DESCRIPTOR.message_types_by_name['protein'] = _PROTEIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ligand = _reflection.GeneratedProtocolMessageType('ligand', (_message.Message,), {
  'DESCRIPTOR' : _LIGAND,
  '__module__' : 'gnina_embeddings_pb2'
  # @@protoc_insertion_point(class_scope:gnina_autoencoder.ligand)
  })
_sym_db.RegisterMessage(ligand)

protein = _reflection.GeneratedProtocolMessageType('protein', (_message.Message,), {
  'DESCRIPTOR' : _PROTEIN,
  '__module__' : 'gnina_embeddings_pb2'
  # @@protoc_insertion_point(class_scope:gnina_autoencoder.protein)
  })
_sym_db.RegisterMessage(protein)


_LIGAND.fields_by_name['embedding']._options = None
# @@protoc_insertion_point(module_scope)
